[project]
name = "ai-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chroma>=0.2.0",
    "chromadb>=1.0.10",
    "langchain[google-genai,openai]>=0.3.25",
    "pandas>=2.2.3",
]
